sudo: required
services:
  - docker

before_install:
  - docker build -t dylancawsey/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dylancawsey/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-458975647698"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"